-- CORREÇÃO SOMATIVA 01 - OFICINA MECÂNICA
create database if not exists OFICINA_MATEUSSILVA;

use OFICINA_MATEUSSILVA;

CREATE TABLE IF NOT EXISTS CLIENTES (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(60) NOT NULL,
    TELEFONE CHAR(15) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    CPF CHAR(14) NOT NULL UNIQUE,
    DATA_NASCIMENTO DATE NOT NULL,
    STATUS_CLIENTE ENUM ('ATIVO', 'INATIVO') DEFAULT 'ATIVO',
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS VEICULOS (
    ID_VEICULO INT AUTO_INCREMENT PRIMARY KEY,
    PLACA_VEICULO CHAR(8) NOT NULL UNIQUE,
    TIPO_VEICULO ENUM ('CARRO', 'MOTO', 'CAMINHAO') DEFAULT 'CARRO',
    COR VARCHAR(20),
    QUILOMETRAGEM INT,
    TIPO_MOTOR ENUM ('ELÉTRICO', 'COMBUSTAO'),
    DATA_CADATRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS MARCAS (
    ID_MARCA INT AUTO_INCREMENT PRIMARY KEY,
    ANO_LANCAMENTO YEAR,
    PAIS_ORIGEM VARCHAR(60),
    STATUS_MARCA ENUM ('ATIVO', 'INATIVO') DEFAULT 'ATIVO',
    NOME_MARCA VARCHAR(30) NOT NULL,
    SITE_MARCA VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS MODELOS (
    ID_MODELO INT AUTO_INCREMENT PRIMARY KEY,
    COR VARCHAR(20),
    ANO_MODELO YEAR,
    VALOR_MODELO DECIMAL (10, 2) NOT NULL,
    CATEGORIA VARCHAR(50),
    NOME_MODELO VARCHAR(50),
    STATUS_MODELO ENUM('ATIVO', 'INATIVO'),
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
    ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_FUNCIONARIO VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    CPF_FUNCIONARIO VARCHAR(14) NOT NULL UNIQUE,
    CARGO VARCHAR(50) NOT NULL,
    SALARIO DECIMAL(10, 2) NOT NULL,
    STATUS_FUNCIONARIO ENUM('ATIVO', 'INATIVO') DEFAULT 'ATIVO',
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS SERVICOS (
    ID_SERVICO INT AUTO_INCREMENT PRIMARY KEY,
    TIPO_SERVICO VARCHAR(60) NOT NULL,
    DESCRICAO_PROBLEMA VARCHAR(250) NOT NULL,
    PRECO_SERVICO DECIMAL(10, 2) DEFAULT 0.00,
    DATA_INICIO DATETIME NOT NULL,
    DATA_TERMINO DATETIME NOT NULL,
    STATUS_SERVICO ENUM('EM ANDAMENTO', 'PENDENTE', 'CONCLUIDO') DEFAULT 'PENDENTE',
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PECAS (
    ID_PECA INT AUTO_INCREMENT PRIMARY KEY,
    TAMANHO VARCHAR(10),
    VALOR DECIMAL(10, 2) NOT NULL,
    NOME_PECA VARCHAR(50),
    VALIDADE DATE NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS_PECA ENUM ('DISPONÍVEL', 'INDISPONÍVEL') DEFAULT 'DISPONÍVEL'
);

CREATE TABLE IF NOT EXISTS ORDEM_DE_SERVICO (
    ID_ORDEM INT AUTO_INCREMENT PRIMARY KEY,
    PRIORIDADE ENUM ('URGENTE', 'SIMPLES') DEFAULT 'SIMPLES',
    PRAZO_FINAL DATE NOT NULL,
    RANKING_ORDEM VARCHAR(40) NOT NULL,
    DATA_EMISSAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TIPO_CASO VARCHAR(250) NOT NULL,
    STATUS_ORDEM ENUM('ATIVO', 'INATIVO') DEFAULT 'ATIVO'
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS (
    ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
    VALOR_TOTAL DECIMAL(10, 2) NOT NULL DEFAULT 000.00,
    FORMA_PAGAMENTO ENUM('DÉBITO', 'CRÉDITO', 'PIX') DEFAULT 'DEBITO' NOT NULL,
    DATA_VENCIMENTO DATE NOT NULL,
    STATUS_PAGAMENTO ENUM ('PAGO', 'PENDENTE') DEFAULT 'PENDENTE',
    COMPROVANTE INT,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FORNECEDORES (
    ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
    RAZAO_SOCIAL VARCHAR(100) NOT NULL,
    CNPJ CHAR(18) NOT NULL UNIQUE,
    TELEFONE_CONTATO VARCHAR(14) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    INSCRICAO_ESTADUAL CHAR(10),
    SEGMENTO_FORNECEDOR VARCHAR(50) NOT NULL,
    ENDERECO_FORNECEDOR VARCHAR(100) NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- VISUALIZAR TODOS OS BD
SHOW SCHEMAS;

-- VISUALIZAR TABELAS DO BD
SHOW TABLES;

-- DESCRIAÇÃO SOBRE INFORMAÇÕES DA TABELA
DESCRIBE CLIENTES;

alter table clientes add idade int;
alter table funcionarios add endereco varchar(30);
alter table marcas add observacao varchar(250);
alter table modelos add tamanho int;
alter table ordens_servico add previsao_finalizacao date;
alter table pecas add categoria_peca varchar(40);
alter table pagamentos add parcelas int;
alter table servicos add observacao varchar(250);
alter table fornecedores add localizacao varchar(100);
alter table veiculos add observacao varchar(250);

-- EXCLUSÃO DE CAMPOS NAS TABELAS
ALTER TABLE CLIENTES DROP COLUMN IDADE;
ALTER TABLE FUNCIONARIOS DROP COLUMN ENDERECO;
ALTER TABLE MARCAS DROP COLUMN OBSERVACAO;
ALTER TABLE MODELOS DROP COLUMN TAMANHO;
ALTER TABLE ORDENS_SERVICO DROP COLUMN PREVISAO_FINALIZACAO;
ALTER TABLE PECAS DROP COLUMN CATEGORIA_PECA;
ALTER TABLE PAGAMENTOS DROP COLUMN PARCELAS;
ALTER TABLE SERVICOS DROP COLUMN OBSERVACAO;
ALTER TABLE FORNECEDORES DROP COLUMN LOCALIZACAO;
ALTER TABLE VEICULOS DROP COLUMN OBSERVACAO;


-- RENOMEAR TABELA
RENAME TABLE MODELOS TO MODELOS_FAB;
RENAME TABLE CLIENTES TO CLIENTES_FAB;
RENAME TABLE FUNCIONARIOS TO FUNCIONARIOS_FAB;
RENAME TABLE MARCAS TO MARCAS_FAB;
RENAME TABLE ORDENS_SERVICO TO ORDENS_SERVICO_FAB;
RENAME TABLE PECAS TO PECAS_FAB;
RENAME TABLE PAGAMENTOS TO PAGAMENTOS_FAB;
RENAME TABLE SERVICOS TO SERVICOS_FAB;
RENAME TABLE FORNECEDORES TO FORNECEDORES_FAB;
RENAME TABLE VEICULOS TO VEICULOS_FAB;

--VISUALIZAR TODOS OS BD
SHOW SCHEMAS;