-- Active: 1788435081430@@127.0.0.1@3306@sesi_cr_tb
CREATE DATABASE SESI_CR_TB;
use SESI_CR_TB;


-- CRIAÇÃO DE TABELAS
CREATE TABLE CLIENTE (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(60) NOT NULL
);

CREATE TABLE PEDIDO (
    ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    DATA_PEDIDO DATETIME NOT NULL,
    ID_CLIENTE INT NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);

-- CONSULTA DE TABELAS
SELECT * FROM cliente;
SELECT * FROM pedido;

-- INSERINDO DADOS NA TABELA
INSERT INTO cliente (NOME_CLIENTE) VALUES
('BRUNO'),
('MARIA'),
('JOSÉ');